/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f0",
        "primary-container": "#2e7d32",
        error: "#ba1a1a",
        "secondary-fixed": "#ffdcc1",
        "on-primary-container": "#cbffc2",
        "on-background": "#191c1c",
        "primary-fixed": "#a3f69c",
        tertiary: "#884200",
        "on-secondary-fixed": "#2e1500",
        "outline-variant": "#bfcaba",
        outline: "#707a6c",
        "surface-variant": "#e1e3e2",
        primary: "#0d631b",
        "on-secondary-fixed-variant": "#6c3a00",
        "secondary-fixed-dim": "#ffb778",
        "on-primary-fixed": "#002204",
        "on-surface-variant": "#40493d",
        "on-error-container": "#93000a",
        "surface-container": "#edeeed",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#005312",
        "primary-fixed-dim": "#88d982",
        background: "#f9f9f8",
        "surface-tint": "#1b6d24",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#723600",
        surface: "#f9f9f8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb786",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e2",
        "on-tertiary-container": "#ffeee6",
        "surface-bright": "#f9f9f8",
        "on-surface": "#191c1c",
        "tertiary-container": "#ad5600",
        "inverse-primary": "#88d982",
        "on-tertiary-fixed": "#311300",
        "error-container": "#ffdad6",
        "on-secondary-container": "#613400",
        "surface-container-low": "#f3f4f3",
        secondary: "#8e4e00",
        "inverse-surface": "#2e3131",
        "secondary-container": "#fd9000",
        "surface-dim": "#d9dad9",
        "tertiary-fixed": "#ffdcc6",
        "surface-container-high": "#e7e8e7",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
